name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.4'

      - name: Build
        run: go build cmd/server/server.go

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.SERVER }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            source: server
            target: /home/ubuntu/
